import { Lato, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SourceFont = Source_Sans_3({
  weight: ['200', '300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-source',
});

const LatoFont = Lato({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
});

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${LatoFont.variable} ${SourceFont.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
